"""додати city_ref та warehouse_ref до orders

Revision ID: 3ed5083ee59b
Revises: c85214c83549
Create Date: 2026-07-19 11:29:03.935515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed5083ee59b'
down_revision: Union[str, None] = 'c85214c83549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('city_ref', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('warehouse_ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'warehouse_ref')
    op.drop_column('orders', 'city_ref')
    # ### end Alembic commands ###
