"""додати case_thickness_mm до products

Revision ID: 51891726c19b
Revises: 3ed5083ee59b
Create Date: 2026-07-19 12:19:31.303365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51891726c19b'
down_revision: Union[str, None] = '3ed5083ee59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('case_thickness_mm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'case_thickness_mm')
    # ### end Alembic commands ###
